spring:
  datasource:
    url: jdbc:mysql://192.168.83.2:3306/sunds?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.atguigu.admin.*  #springbean监控
      filters: stat,wall,slf4j  #所有开启的功能

      stat-view-servlet:  #监控页配置
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:  #web监控
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: #sql监控
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false
#    type:

  redis:
    host: 192.168.83.2
    port: 6379
#    password: lfy:Lfy123456
    client-type: jedis
    jedis:
      pool:
        max-active: 10



  jdbc:
    template:
      query-timeout: 3

# 配置mybatis规则、使用MyBatisPlus则此项配置无效
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:  # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true